[package]
name = "rsml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlir-sys = { git = "https://github.com/ArtemSkrebkov/mlir-sys.git", branch = "main"}
